### PR TITLE
Bootstrap infrastructure

### PR DESCRIPTION
**Pull request by altayhunoglu**
Adds Bootstrap infrastructure.
It means, we can use all of the components here:
https://react-bootstrap.github.io/components/alerts

### CODE REVIEW

**Comment by ErdemT09** [comment]
image

Do I need to upload something?

**Comment by altayhunoglu** [comment]
Erdem, I am sorry it is my fault that I forget to warn you. 

You should do:

**npm install** after adding a new library like **react-bootstrap**, to install the library into your local node_modules directory.

**Comment by ErdemT09** [comment]
https://react-bootstrap.github.io/getting-started/introduction/
I've now done the `npm install part. However, it's still yielding failure, but in a different way:`

**Comment by altayhunoglu** [comment]
Can you just clean the project and try again?

**Comment by ErdemT09** [comment]
> Can you just clean the project and try again?

What is exactly "cleaning a project"?

**Comment by ErdemT09** [comment]
I just had to install it to the right place: directly into the project folder. It works well now.

**Comment by ErdemT09** [comment]
Is there anything that makes this button special when compared to a normal HTML button?

**Comment by altayhunoglu** [comment]
Functionally, it does not add anything special.
 It is more about aesthetics, and especially responsiveness which is as important as the functionality according to an average end-user.

**Comment by ErdemT09** [comment]
But this Button doesn't have anything responsive with it yet. Is this true?

**Comment by ErdemT09** [comment]
Note: https://react-bootstrap.github.io/components/cards/
Card Groups might be useful, if there isn't anything better.

**Comment by altayhunoglu** [comment]
We need to add extra Bootsrap CSS classes (like `btn-block`) into the current Button tag. But which CSS we will add depends on the position of the button at that time.

**Comment by altayhunoglu** [comment]
> Note: https://react-bootstrap.github.io/components/cards/
> `Card Groups` might be useful, if there isn't anything better.

If you mean for the "Product", I thought the same indeed.
Can you try to do this?

**Comment by ErdemT09** [comment]
> If you mean for the "Product", I thought the same indeed.
> Can you try to do this?

I will try. Let's merge this PR then.

**Review by ErdemT09 — APPROVED** [review]

**Comment by altayhunoglu** [comment]
You can limit the list to "Top 3 products" for now.

**Pull request merged**
