### PR TITLE
 Sign-up, Sign-in, Profile, Admin-Moderator-User Board initial codes.

### PR DESCRIPTION
**Pull request by altayhunoglu**
## Authentication

- `SignupPage` and `LoginPage` are backed by Redux currently.
- In `LoginPage` I prefer using the `useDispatch` hook as an example, instead of using connect to map function to props.
- When a user logs in to the backend, the backend side generates a JWT token. We store user information including the token in localStorage like this, in `auth.service.js`:
 
```js
  localStorage.setItem("user", JSON.stringify(response.data));
 ```
 When we need the current user's information back, we will just getItem. For example, we create our new `header` with a token like this, in `auth-header.js`:
 
```
 export default function authHeader() {
  const user = JSON.parse(localStorage.getItem("user"));

  let headers = {
    'Content-Type': 'application/json'
  }
  if (user && user.accessToken) {
       headers['Authorization'] = "Bearer " + user.accessToken;

  }
    return headers;
}
```

> **If the header contains a token, the server will know that the user has logged in so he has access to restricted services.**
 
# Authorization:

 In order to be able to test the roles, the reviewer should set roles in the database manually (as we do not have an admin panel yet.)
 
These are the roles users may have:

image

This indicates that the user with id=1 has ROLE_USER and ROLE_MODERATOR roles.
So the user can see the "Moderator Board" link on the navigation bar.
In order to be able to see "Admin Board", one needs to have the ROLE_ADMIN role.

image

## Note:

  We need to add form validation on the client side.
       -  Email must include `@` character with at most 50 characters.
       -  Username must have at least 3, at most 20 characters.
       -  Password must have at least 6, at most 40 characters.

### CODE REVIEW

**Comment by altayhunoglu** [comment]
Accidentally pushed by Spiralgo. Pretty sorry about that.

**Comment by ErdemT09** [comment]
How can I test these features?

**Comment by ErdemT09** [comment]
https://react-bootstrap.github.io/components/forms/#forms-validation-libraries

We can perhaps use Formik for client-side validation in the future.

**Comment by altayhunoglu** [comment]
Yes. It is not that difficult so we can leave it for now.

**Review by ErdemT09 — APPROVED** [review]
For now, I don't understand much of this structure but it mostly works fine. 

We will eventually need to add more layers into these profiles, with user-data from purchases, user-groups etc. There are a lot of requirements on the way.

Our progress is although well enough, for which I'm thankful to you.

**Pull request merged**
